### ISSUE TITLE
issue with js/css imports inside injected html file

### ISSUE THREAD

**Issue by mdrahiem** [altrusl/vite-plugin-html-injection#1]
Hey @altrusl Thanks for the plugin. It works great. I am new to Vite eco system and I found your plugin very helpful for my use case. I just have one issue though. The `css` or `js` files imported in the injected_html_file are not working and the browser shows they are not found. I have put the files in `src/` directory itself along with the html file. Any ideas on how to solve this?

I have created a sandbox.
https://codesandbox.io/p/devbox/vite-plugin-html-injection-grpf65?file=/src/sample/index.html:16,50

Please let me know if my question is not clear.

**Comment by altrusl** [comment]
Hello @mdrahiem 
You should move `sample/data` directory to `public` and insert chunks to head and body separately
I modified your sandbox:
https://codesandbox.io/p/devbox/vite-plugin-html-injection-forked-jrdqg9

**Comment by mdrahiem** [comment]
Thanks much for the updated sandbox @altrusl. It's clear now. May I ask one more question. What if I want to inject in a specific route instead of the root file? In this way, I think I can inject multiple html files in different routes.

**Comment by altrusl** [comment]
> Thanks much for the updated sandbox @altrusl. It's clear now. May I ask one more question. What if I want to inject in a specific route instead of the root file? In this way, I think I can inject multiple html files in different routes.

No, it works with index.html currently
But you can fork/copy it and change the code to handle multiplу entries

**Comment by mdrahiem** [comment]
Thanks. I will check it out. If I am able to achieve it I will create a PR. 😅
