### ISSUE TITLE
Feature Request: Support for Dynamic Code Injection

### ISSUE THREAD

**Issue by martinkutter** [altrusl/vite-plugin-html-injection#3]
Thank you for your awesome plugin 🙏

For my current project, the plugin does not offer enough flexibility. I would like to inject dynamic code (List of supported Browsers) instead of loading static code from a file. Are you willing to incorporate this functionality into the plugin? If so, I would be happy to prepare a pull request.

**Comment by altrusl** [comment]
Yes, Martin, go ahead

**Comment by martinkutter** [comment]
I go ahead using https://www.npmjs.com/package/vite-plugin-insert-html
So there is no need for a new function on my part.
